### PR TITLE
Add VIRTUAL to dataTypes

### PR DESCRIPTION
**Pull request by joeybaker**
Simple fix to allow virtual datatypes to work

### CODE REVIEW

**Comment by joeybaker** [comment]
Updated to include tests

**Comment by mibrito** [comment]
Sorry for taking so long! Thanks a lot for your contribution, as soon as possible I will publish on npm and I will also include it on change log.

**Comment by joeybaker** [comment]
Great. Thanks @mibrito.

**Comment by mibrito** [comment]
I published at npm ;)

**Pull request merged**
